export type TournamentResponse = {
  tournament: Tournament;
};

export type Tournament = {
  id: number;
  name: string;
  url: string;
  description: string;
  tournament_type: string;
  started_at: string | null;
  completed_at: string | null;
  require_score_agreement: boolean;
  notify_users_when_matches_open: boolean;
  created_at: string;
  updated_at: string;
  state: string;
  open_signup: boolean;
  notify_users_when_the_tournament_ends: boolean;
  progress_meter: number;
  quick_advance: boolean;
  hold_third_place_match: boolean;
  pts_for_game_win: string;
  pts_for_game_tie: string;
  pts_for_match_win: string;
  pts_for_match_tie: string;
  pts_for_bye: string;
  swiss_rounds: number;
  private: boolean;
  ranked_by: string;
  show_rounds: boolean;
  hide_forum: boolean;
  sequential_pairings: boolean;
  accept_attachments: boolean;
  rr_pts_for_game_win: string;
  rr_pts_for_game_tie: string;
  rr_pts_for_match_win: string;
  rr_pts_for_match_tie: string;
  created_by_api: boolean;
  credit_capped: boolean;
  category: string | null;
  hide_seeds: boolean;
  prediction_method: number;
  predictions_opened_at: string | null;
  anonymous_voting: boolean;
  max_predictions_per_user: number;
  signup_cap: number | null;
  game_id: number;
  participants_count: number;
  group_stages_enabled: boolean;
  allow_participant_match_reporting: boolean;
  teams: boolean;
  check_in_duration: number | null;
  start_at: string;
  started_checking_in_at: string | null;
  tie_breaks: string[];
  locked_at: string | null;
  event_id: number | null;
  public_predictions_before_start_time: boolean;
  ranked: boolean | null;
  grand_finals_modifier: string | null;
  predict_the_losers_bracket: boolean;
  spam: boolean | null;
  ham: boolean | null;
  rr_iterations: number | null;
  tournament_registration_id: number | null;
  donation_contest_enabled: boolean | null;
  mandatory_donation: boolean | null;
  non_elimination_tournament_data: {
    participants_per_match: string;
  };
  auto_assign_stations: boolean | null;
  only_start_matches_with_stations: boolean | null;
  registration_fee: string;
  registration_type: string;
  split_participants: boolean;
  allowed_regions: string[];
  show_participant_country: boolean | null;
  program_id: number | null;
  program_classification_ids_allowed: number[] | null;
  team_size_range: [number, number] | null;
  toxic: boolean | null;
  use_new_style: boolean | null;
  optional_display_data: {
    show_standings: string;
    show_announcements: boolean;
  };
  processing: boolean;
  oauth_application_id: number | null;
  hide_bracket_preview: boolean;
  consolation_matches_target_rank: number | null;
  review_swiss_pairings_before_starting_rounds: boolean | null;
  allow_incomplete_rosters: boolean | null;
  check_in_onsite: boolean;
  participants: { participant: Participant }[];
  matches: { match: Match }[];
};

export type Participant = {
  id: number;
  tournament_id: number;
  name: string;
  seed: number;
  active: boolean;
  created_at: string;
  updated_at: string;
  invite_email: string | null;
  final_rank: number | null;
  misc: string | null;
  icon: string | null;
  on_waiting_list: boolean;
  invitation_id: number | null;
  group_id: number | null;
  checked_in_at: string | null;
  ranked_member_id: number | null;
  custom_field_response: string | null;
  clinch: string | null;
  integration_uids: string | null;
  challonge_username: string | null;
  challonge_user_id: number | null;
  challonge_email_address_verified: boolean | null;
  removable: boolean;
  participatable_or_invitation_attached: boolean;
  confirm_remove: boolean;
  invitation_pending: boolean;
  display_name_with_invitation_email_address: string;
  email_hash: string | null;
  username: string | null;
  display_name: string;
  attached_participatable_portrait_url: string | null;
  can_check_in: boolean;
  checked_in: boolean;
  reactivatable: boolean;
  check_in_open: boolean;
  group_player_ids: number[];
  has_irrelevant_seed: boolean;
  ordinal_seed: string;
  roster_complete: boolean | null;
  roster_size: number | null;
};

export type Match = {
  isHidden?: boolean | null
  isCollapse?: boolean | null
  id?: number;
  tournament_id?: number;
  state?: 'open' | 'pending' | 'complete';
  player1_id?: number | null;
  player2_id?: number | null;
  player1_prereq_match_id?: number | null;
  player2_prereq_match_id?: number | null;
  player1_is_prereq_match_loser?: boolean;
  player2_is_prereq_match_loser?: boolean;
  winner_id?: number | null;
  loser_id?: number | null;
  started_at?: string | null;
  created_at?: string;
  updated_at?: string;
  identifier?: string;
  has_attachment?: boolean;
  round: number;
  player1_votes?: number | null;
  player2_votes?: number | null;
  group_id?: number | null;
  attachment_count?: number | null;
  scheduled_time?: string | null;
  location?: string | null;
  underway_at?: string | null;
  optional?: boolean;
  completed_at?: string | null;
  suggested_play_order?: number;
  forfeited?: boolean | null;
  open_graph_image_file_name?: string | null;
  open_graph_image_content_type?: string | null;
  open_graph_image_file_size?: number | null;
  prerequisite_match_ids_csv?: string;
  scores_csv?: string;
};
